version: '3.8'

services:
  # NestJS App Service
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-nest-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb  
    environment:
      MONGO_URI: "mongodb://mongodb:27017/" 
      MONGO_USER: "admin"              
      MONGO_PASSWORD: "admin"   
    volumes:
      - .:/app

  # Nginx Service
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: my-nginx
    ports:
      - "80:80"
    depends_on:
      - nestjs-app

  # MongoDB Service
  mongodb:
    image: mongo
    container_name: my-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"       # Update with your MongoDB root username
      MONGO_INITDB_ROOT_PASSWORD: "admin"       # Update with your MongoDB root password
      # MONGO_INITDB_DATABASE: "mydatabase"                    # Update with your desired database name
